### ISSUE TITLE
Flight broken

### ISSUE THREAD

**Issue by JibberishGulp** [drgmes/doctor-who-mod#3]
Flight seems to be broken in fabric 1.20.1, you can activate the flight fine but once it teleports most buttons become non-functional and you cant get the door open. Some things can still be pressed/interacted with, but anything relating to the fight seems to break

**Comment by drgmes** [comment]
Hello! For temporary solution you can break the console unit and put it again (for checking which controls are usable now you can use F3+B, that hotkeys shows entity hitboxes). I will try to recreate your problem and fix it. What mods are you using alongside dwm?

**Comment by JibberishGulp** [comment]
Hi i tried it with no mods and it still had that error, i am using fabric api 0.83.1 if that causes any problems (expect architerctury)

**Comment by drgmes** [comment]
@JibberishGulp what says the "Materialized" line on the console screen? Looks like you didn't materialize. Maybe the last time when you started flight, you ran out of fuel and the TARDIS didn't find a safe coordinate to make an emergency landing on.

In this case, when you are not materialized, you cannot use most of the levers and buttons, that's right. If this is the problem, it must be confirmed and then we can think about how to get out of this situation inside the game.

To make sure it's not a technical issue, could you send a F3+B screenshot like this?

![2023-07-11_20 00 38](https://github.com/drgmes/doctor-who-mod/assets/33026426/c96a120d-b316-4c1c-a425-3248ce939489)

**Comment by JibberishGulp** [comment]
Hi, yes that all looks fine, I try to follow all the steps in the video but it never materializes me out after the flight. It is not a fuel issue as have waited for it to get full. I tried updating to the version you released today but sadly my problem hasn't changed from what I can tell. No matter what I do it never materializes after I use it.
![2023-07-11_13 26 55](https://github.com/drgmes/doctor-who-mod/assets/102432947/a235deda-8a73-4334-89b4-5e72931ad3b7)
![2023-07-11_13 27 00](https://github.com/drgmes/doctor-who-mod/assets/102432947/dfab6385-b76d-49d8-a995-8a1786056422)
![2023-07-11_13 27 39](https://github.com/drgmes/doctor-who-mod/assets/102432947/ee0f354c-15be-40a8-b9f1-6c47e33f2a1f)
![2023-07-11_13 29 27](https://github.com/drgmes/doctor-who-mod/assets/102432947/b3ba273d-ba20-48f2-a88f-e7b427983da6)
![2023-07-11_13 29 33](https://github.com/drgmes/doctor-who-mod/assets/102432947/260b97dc-bdfc-4ca6-9347-cfb77ff496b8)

**Comment by JibberishGulp** [comment]
Yeah, i tried updating the fabric api, mod and architerctury, and I followed the video exactly but it refuses to materialize after the flight. Also, i dont see it on the page anywhere but the fabric version of the mod does say "fabricconfigapiport" is required for it to run. Considering everything else works fine it might be a small issue with the port, because otherwise the mod seems to work perfectly

**Comment by drgmes** [comment]
@JibberishGulp yes, **Forge**ConfigApiPort is required and it must be listed in dependencies of Fabric file on CurseForge. Also the game must refuse to launch if that api-mod was not found, so i doubt the problem is in that

I'm trying to recreate your problem, but I always materialize after a flight. I hope sending your logs (from {MINECRAFT_PATH}/logs) right after completing a flight helps. Maybe there is some crash in landing destination calculation or something

**Comment by JibberishGulp** [comment]
I attached the latest log file, it seems like it un-materalizes but the flight itself just never starts. If it helps i can attach a video on the procress im doing, could just be user error as the video seems slighty wrong (the handle level doesnt flick, only the up and down button does)
[latest.log](https://github.com/drgmes/doctor-who-mod/files/12018078/latest.log)

**Comment by drgmes** [comment]
@JibberishGulp yes, attach the video please from the beginning, it will be just great! Logs seems clear

**Comment by JibberishGulp** [comment]
Here it is, I kinda just tested things out in the video, like I've said the only thing that seems wrong is that the lever not working, but from what I understand everything I did should be what you have to do for it to work. Im sorry if this has been some kind of stupid user error this whole time. Dont know why the audio also didnt work in the video but the sounds played correct just the flight never started.

https://youtu.be/YtkWlYiJkGA

**Comment by drgmes** [comment]
@JibberishGulp Thank you for the video, i think i got it.

The fact is that levers and sliders have different clicking logic for the left and right mouse buttons. For example, the coordinate lever with left mouse button click will decrease the value, the right click will increase it. Such logic have: coordinate levers, vertical scanning lever, scaling lever, flight start lever, handbrake lever, materialization slider button. This was done in order to prevent miss clicks

This is not your omission, it only means that the interface is not entirely clear. Give it a try, if that's really the case, I'll think about how I can improve this point: maybe a simple description of this logic on the mod page will be enough, or I'll change the behavior

**Comment by JibberishGulp** [comment]
Hi yes it worked perfectly,  i cant believe i didnt discover that this entire time. I dont think the system is bad but because most mods break with you mine them i cant say i wouldve ever tried it without reading it somewhere, if your thinking about changing it maybe an interact button might be more clear. Before I end this ticket is there a config file to edit the spawn rate of the tardis?

**Comment by drgmes** [comment]
@JibberishGulp Great!

The spawn rate can be customized by creating your custom datapack (this wiki [might](https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack) help). The file "(DoctorWhoMod-1.20.1-fabric-1.0.2.jar as archive)data/dwm/worldgen/placed_feature/abandoned_tardis_{surface|underground|nether}.json" must be overridden in the datapack. I think changing the "chance" parameter for minecraft:rarity_filter is what you need now, but in the future I plan to change the TARDIS generation a little or completely redo the approach, because now there are too many of them in the world. But it only plans for now :)

**Comment by JibberishGulp** [comment]
Thank you for the cool mod, sorry about the trouble man. Take care
